---
- name: Reiniciar contenedor BancoNova
  community.docker.docker_container:
    name: "{{ app_nombre }}-{{ ambiente }}"
    state: started
    restart: true
    comparisons:
      '*': ignore
  become: true
