apiVersion: v1
kind: Service
metadata:
  name: banconova-service
  namespace: banconova-produccion
  labels:
    app: banconova
    ambiente: produccion
spec:
  type: NodePort
  selector:
    app: banconova
    ambiente: produccion
  ports:
  - name: http
    protocol: TCP
    port: 6000
    targetPort: 6000
    nodePort: 30002
    # Acceso: http://localhost:30002
